spring:
  application:
    name: config-server-bus
  cloud:
    config:
      server:
        git:
          uri: https://github.com/story-has-you/spring-boot-example.git
          search-paths: spring-cloud/spring-cloud-config-server-bus/repo
          # 强制拉取
          force-pull: true
  rabbitmq:
    addresses: 47.101.214.214:5672
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://www.mingrxiy.com:8761/eureka/

server:
  port: 8888

# 动态刷新需要添加的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always