spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://127.0.0.1:9411
server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://www.mingrxiy.com:8761/eureka/
