spring:
  application:
    name: spring-cloud-sleuth
  sleuth:
    sampler:
      # 采样方式100%
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411
server:
  port: 9009

eureka:
  client:
    service-url:
      defaultZone: http://www.mingrxiy.com:8761/eureka/
