spring:
  application:
    name: eureka-server-peer2
server:
  port: 10002

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
    fetch-registry: false
    register-with-eureka: false
