spring:
  application:
    name: spring-cloud-dubbo-consumer
  main:
    allow-bean-definition-overriding: true

dubbo:
  scan:
    base-packages: com.storyhasyou.example.cloud.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

server:
  port: 8080