spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/story-has-you/spring-boot-example.git
          search-paths: spring-cloud/spring-cloud-config-server/repo
          # 强制拉取
          force-pull: true

server:
  port: 8888