spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/story-has-you/spring-boot-example.git
          search-paths: spring-cloud/spring-cloud-config-server/repo
          # 强制拉取
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://www.mingrxiy.com:8761/eureka/

server:
  port: 8888

