server:
  port: 8001

spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: 123456
    connection-timeout: 15000
    # 生产者配置: 启动消息确认模式
    publisher-confirm-type: correlated
    listener:
      simple:
        # 消费者配置: 表示消费成功之后需要手工进行签收(ack)，默认为auto
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        # 消费者配置: 批量消息消费则一条条的消费
        prefetch: 1

    # 生产者配置: 设置return消息模式，需要和mandatory一起使用
#    publisher-returns: true
#    template:
#      mandatory: true

